package com.Sync.Notification.api.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Getter;
import lombok.Setter;

@Entity
@Getter
@Setter
@Table(name = "RESULT_2")
public class NotifyHistory {
	@Id
	@Column(name = "Result_ID")
	private int resultId;
	@Column(name = "Client_ID")
	private int clientId;
	@Column(name = "Job_ID")
	private int jobId;
	@Column(name = "Instance_ID")
	private int instanceId;
	@Column(name = "Data_Row_ID")
	private int datarowId;
	@Column(name = "Data_Key_Code")
	private String datakeyCode;
	@Column(name = "Data_Key_Code_2")
	private String datakeyCode2;
	@Column(name = "Data_Key_Code_3")
	private String datakeyCode3;
	@Column(name = "Data_Key_Code_4")
	private String datakeyCode4;
	@Column(name = "Data_Key_Code_5")
	private String datakeyCode5;
	@Column(name = "Data_Key_Code_6")
	private String datakeyCode6;
	@Column(name = "Data_Open_Date")
	private String dataopenDate;
	@Column(name = "Data_Record_Type")
	private String datarecordType;
	@Column(name = "Data_C_SSN_TaxID")
	private String datacssntaxId;
	@Column(name = "Data_S_SSN_TaxID")
	private String datasssntaxId;
	@Column(name = "Data_S_SSN_TaxID_4")
	private String datasssntaxId4;
	@Column(name = "Data_S_Full_Name")
	private String datasfullName;
	@Column(name = "Data_S_First_Name")
	private String datasfirstName;
	@Column(name = "Data_S_Middle_Name")
	private String datasmiddleName;
	@Column(name = "Data_S_Last_Name")
	private String dataslastName;
	@Column(name = "Data_S_Generation")
	private String datasGeneration;
	@Column(name = "Data_S_Company")
	private String datasCompany;
	@Column(name = "Data_S_Root_First")
	private String datasrootFirst;
	@Column(name = "Data_S_Address_Street_Name")
	private String datasaddressstreetName;
	@Column(name = "Data_S_City")
	private String datasCity;
	@Column(name = "Data_S_State")
	private String datasState;
	@Column(name = "Data_S_Zip")
	private String datasZip;
	@Column(name = "Data_S_Zip_4")
	private String datasZip4;
	@Column(name = "Matched_Debtor_ID")
	private int matcheddebtorID;
	@Column(name = "Debtor_Clean_First_Name")
	private String debtorcleanfirstName;
	@Column(name = "Debtor_Clean_Middle_Name")
	private String debtorcleanmiddleName;
	@Column(name = "Debtor_Clean_Last_Name")
	private String debtorcleanlastName;
	@Column(name = "Debtor_Clean_Generation")
	private String debtorcleangeneration;
	@Column(name = "Debtor_Clean_Company_Name")
	private String debtorcleancompanyName;
	@Column(name = "Debtor_SSN_TaxID")
	private String debtorssntaxID;
	@Column(name = "Debtor_SSN_TaxID_4")
	private String debtorssntaxID4;
	@Column(name = "Debtor_Type")
	private String debtorType;
	@Column(name = "Debtor_Prefix")
	private String debtorPrefix;
	@Column(name = "Debtor_First_Name")
	private String debtorfirstName;
	@Column(name = "Debtor_Middle_Name")
	private String debtormiddleName;
	@Column(name = "Debtor_Last_Name")
	private String debtorlastName;
	@Column(name = "Debtor_Company_Name")
	private String debtorcompanyName;
	@Column(name = "Debtor_Generation")
	private String debtorGeneration;
	@Column(name = "Debtor_AKA")
	private String debtorAka;
	@Column(name = "Debtor_AKA_2")
	private String debtorAka2;
	@Column(name = "Debtor_DBA")
	private String debtorDba;
	@Column(name = "Debtor_DBA_2")
	private String debtorDba2;
	@Column(name = "Debtor_Root_First")
	private String debtorrootFirst;
	@Column(name = "Debtor_Code")
	private String debtorCode;
	@Column(name = "Matched_Address_ID")
	private int matchedaddressId;
	@Column(name = "Matched_Address_Category")
	private String matchedaddressCategory;
	@Column(name = "Debtor_Address_Line_1")
	private String debtoraddressLine1;
	@Column(name = "Debtor_Address_Line_2")
	private String debtoraddressLine2;
	@Column(name = "Debtor_Address_Number")
	private String debtoraddressNumber;
	@Column(name = "Debtor_Address_Pre_Direction")
	private String debtoraddresspreDirection;
	@Column(name = "Debtor_Address_StreetName")
	private String debtoraddressstreetName;
	@Column(name = "Debtor_Address_Suffix")
	private String debtoraddressSuffix;
	@Column(name = "Debtor_Address_Post_Direction")
	private String debtoraddresspostDirection;
	@Column(name = "Debtor_Address_Suite_Name")
	private String debtoraddresssuiteName;
	@Column(name = "Debtor_Address_Suite_Number")
	private String debtoraddresssuiteNumber;
	@Column(name = "Debtor_City")
	private String debtorCity;
	@Column(name = "Debtor_State")
	private String debtorState;
	@Column(name = "Debtor_Zip")
	private String debtorZip;
	@Column(name = "Debtor_Zip_4")
	private String debtorZip4;
	@Column(name = "Debtor_Clean_Address_Street_Name")
	private String debtorcleanaddressstreetName;
	@Column(name = "Debtor_Clean_City")
	private String debtorcleanCity;
	@Column(name = "Spouse_SSN")
	private String spouseSsn;
	@Column(name = "Spouse_Prefix")
	private String spousePrefix;
	@Column(name = "Spouse_First_Name")
	private String spousefirstName;
	@Column(name = "Spouse_Middle_Name")
	private String spousemiddleName;
	@Column(name = "Spouse_Last_Name")
	private String spouselastName;
	@Column(name = "Spouse_Generation")
	private String spouseGeneration;
	@Column(name = "Spouse_AKA")
	private String spouseAka;
	@Column(name = "Spouse_AKA_2")
	private String spouseAka2;
	@Column(name = "Spouse_DBA")
	private String spouseDba;
	@Column(name = "Spouse_DBA_2")
	private String spouseDba2;
	@Column(name = "Spouse_Code")
	private String spouseCode;
	@Column(name = "Spouse_Address_Line_1")
	private String spouseaddressLine1;
	@Column(name = "Spouse_Address_Line_2")
	private String spouseaddressLine2;
	@Column(name = "Spouse_Address_Number")
	private String spouseaddressNumber;
	@Column(name = "Spouse_Address_Pre_Direction")
	private String spouseaddresspreDirection;
	@Column(name = "Spouse_Address_Street_Name")
	private String spouseaddressstreetName;
	@Column(name = "Spouse_Address_Suffix")
	private String spouseaddressSuffix;
	@Column(name = "Spouse_Address_Post_Direction")
	private String spouseaddresspostDirection;
	@Column(name = "Spouse_Address_SuiteName")
	private String spouseaddresssuiteName;
	@Column(name = "Spouse_Address_Suite_Number")
	private String spouseaddresssuiteNumber;
	@Column(name = "Spouse_City")
	private String spouseCity;
	@Column(name = "Spouse_State")
	private String spouseState;
	@Column(name = "Spouse_Zip")
	private String spouseZip;
	@Column(name = "Spouse_Zip_4")
	private String spouseZip4;
	@Column(name = "Case_ID")
	private int caseId;
	@Column(name = "Match_Source")
	private String matchSource;
	@Column(name = "Match_Level")
	private String matchLevel;
	@Column(name = "Match_Root_First")
	private int matchrootFirst;
	@Column(name = "Match_First_Name")
	private int matchfirstName;
	@Column(name = "Match_Middle_Name")
	private int matchmiddleName;
	@Column(name = "Match_Last_Name")
	private int matchlastName;
	@Column(name = "Match_Generation")
	private int matchGeneration;
	@Column(name = "Match_Full_Name")
	private int matchfullName;
	@Column(name = "Match_Company_Name")
	private int matchcompanyName;
	@Column(name = "Match_Address_Street")
	private int matchaddressStreet;
	@Column(name = "Match_Address_City")
	private int matchaddressCity;
	@Column(name = "Match_Address_State")
	private int matchaddressState;
	@Column(name = "Match_Address_Zip_5")
	private int matchaddressZip5;
	@Column(name = "Match_Address_Zip_4")
	private int matchaddressZip4;
	@Column(name = "Match_SSN")
	private int matchSsn;
	@Column(name = "Match_Redacted_SSN")
	private int matchredactedSsn;
	@Column(name = "Match_Phone_Number")
	private int matchphoneNumber;
	@Column(name = "Match_Case")
	private int matchCase;
	@Column(name = "Match_Court")
	private int matchCourt;
	@Column(name = "Notice_Type")
	private String noticeType;
	@Column(name = "Notify_Type")
	private int notifyType;
	@Column(name = "Date_Entered")
	private String dateEntered;
	@Column(name = "Update_Date")
	private String updateDate;
	@Column(name = "Data_S_Gender_Cast")
	private String datasgenderCast;
	@Column(name = "Debtor_Gender_Cast")
	private String debtorgenderCast;
	@Column(name = "Data_S_Address_Number")
	private String datasaddressNumber;
	@Column(name = "Match_Gender")
	private int matchGender;
	@Column(name = "Match_Address_Number")
	private int matchaddressNumber;
	@Column(name = "Match_First_Last")
	private int matchfirstLast;
	@Column(name = "Match_Middle_Last")
	private int matchmiddleLast;
	@Column(name = "Total_Match")
	private int totalMatch;

}
